name: CI

on: [push]

jobs:
  build:
      runs-on: ubuntu-latest

      steps: 
      - uses: actions/checkout@v1
      - name: run one-line script
      - run: echo "hello there"
      - name: run multi-line script
      - run: |
        echo "add other actions"
        echo "test and deploy etc"
