name: Lambda CI

on: 
  push:
    branches:
      - master
    paths:
      - './src/TestFunction/*'
      - './src/xlk_flask/*'
      - '.github/workflows/main.yml'

jobs:
  deploy-node:
      runs-on: ubuntu-latest

      steps: 

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Diff Check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./src/TestFunction/* | grep -qE '(\.mjs)$'; then
            echo "changes_detected=true" >> "$GITHUB_ENV"
          else
            echo "changes_detected=false" >> "$GITHUB_ENV"
          fi

      - name: Package
        run: |
          cd ./src/TestFunction
          zip -r $GITHUB_WORKSPACE/function.zip ./.

      - name: Connect
        if: env.changes_detected == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTFUNCTION_LAMBDA_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TESTFUNCTION_LAMBDA_ACCESS_SECRET }}
          aws-region: us-west-2

      - name: Deploy
        if: env.changes_detected == 'true'
        run: aws lambda update-function-code --function-name TestFunction --zip-file fileb://function.zip

      - name: Echo Success
        run: echo "NODE success" >> $GITHUB_STEP_SUMMARY

  deploy-flask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      
# need to implement diff check

      - name: Dependencies
        run: |
          pip install -r ./src/xlk_flask/requirements.txt
          pip install aws-wsgi boto3

      - name: Package
        run: |
          cd ./src/xlk_flask
          zip -r $GITHUB_WORKSPACE/function.zip ./.
  
      - name: Connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.XLK_COUNTER_LAMBDA_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.XLK_COUNTER_LAMBDA_ACCESS_SECRET }}
          aws-region: us-west-2

      - name: Deploy
        run: aws lambda update-function-code --function-name xlk-user-button-counter-increment --zip-file fileb://function.zip
  
      - name: Echo Success
        run: echo "FLASK success" >> $GITHUB_STEP_SUMMARY
