name: Lambda CI

on: 
  push:
    branches:
      - master
    paths:
      - './src/TestFunction/.'
      - './src/xlk_flask/.'

jobs:
  deploy-node:
      runs-on: ubuntu-latest

      steps: 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Diff Check
        id: code-changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./src/TestFunction/. | grep -qE '(\.mjs)$'; then
            echo "::set-output name=changes_detected::true"
          else
            echo "::set-output name=changes_detected::false"
          fi

      - name: Package
        run: |
          cd ./src/TestFunction
          zip -r $GITHUB_WORKSPACE/function.zip ./.

      - name: Deploy
        if: steps.code-changes.outputs.changes_detected == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTFUNCTION_LAMBDA_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TESTFUNCTION_LAMBDA_ACCESS_SECRET }}
          aws-region: us-west-2
      - run: aws lambda update-function-code --function-name TestFunction --zip-file fileb://function.zip

      - name: Echo Success
        run: echo "success" >> $GITHUB_STEP_SUMMARY

