name: Lambda CI

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest

      steps: 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Package
        run: zip -r function.zip ./src/TestFunction

      - name: Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTFUNCTION_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TESTFUNCTION_ACCESS_SECRET }}
          aws-region: us-west-2
      - run: aws lambda update-function-code --function-name TestFunction --zip-file fileb://function.zip

      - name: Echo Success
        run: echo "success" >> $GITHUB_STEP_SUMMARY

